apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: timebillingapi-secret
  namespace: timebillingapi
spec:
  template:
    metadata:
      creationTimestamp: null
      name: timebillingapi-secret
      namespace: timebillingapi
