apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: timebillingmonolith-secret
  namespace: timebilling
spec:
  template:
    metadata:
      creationTimestamp: null
      name: timebillingmonolith-secret
      namespace: timebilling
