apiVersion: apps/v1
kind: Deployment
metadata:
  name: timebillingweb
  labels:
    app: timebillingweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timebillingweb
  template:
    metadata:
      labels:
        app: timebillingweb
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
    spec:
      containers:
      - name: timebillingweb
        image: registry:5000/timebillingweb:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: timebillingweb-configmap
        ports:
        - containerPort: 80
          name: http

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: timebillingweb-configmap
data:
  DOTNET_ENVIRONMENT: "Production"
  ASPNETCORE_ENVIRONMENT: "Production"
